### ISSUE TITLE
No rule to make target libexpropt.a

### ISSUE THREAD

**Issue by xiongdl** [asyncvlsi/dflowmap#1]
Hi, I have download the source code of dflowmap, and install it by following steps:
unzip dflowmap-main.zip
cd dflowmap-main
sh build.sh
cd ..

But the process has some error:
No rule to make target libexpropt.a, needed by src/dflowmap Stop. 

How to solve the problem?

Thanks!

**Comment by RuiLi92** [comment]
Hi! I have fixed the dependency issues on the cmake file, so if you download the latest code, it should work properly.

More specifically, dflowmap tries to do logic optimizations and performance modeling for the customized function unit processes (e.g., optimize the process "a + b * c"). In order to do that, users need to install the expression optimization tool first. That tool will be released soon.

Please let me know if the latest changes fix the issues on your side.

**Comment by RuiLi92** [comment]
@xiongdl Hi, does the latest code solve the issue on your side?

**Comment by xiongdl** [comment]
Hi Ruili92,
I download the latest code, and the original problem has been fixed, but the installation is still failed. I use GCC-8.5.0 and CMake-3.16.6, and the environment is Cent-OS 7.4. 

The Install command is:
   cd dflowmap-main
   sh build.sh

The Error is :
   dflowmap-main/src/core/NameGenerator.cc:122:3: error: "act_expr_collect_ids" was not declared in this scope.
           act_expr_collect_ids(arg_list, expr);
  dflowmap-main/src/core/NameGenerator.cc:123:10: error: "act_expr_to_string" was not declared in this scope.
           act_expr_to_string(arg_list, expr);

Thanks.

**Comment by RuiLi92** [comment]
Hi, you need to download the latest ACT code (https://github.com/asyncvlsi/act) and install it on your local machine before running dflowmap. dflowmap is using two new APIs (`act_expr_collect_ids` and `act_expr_to_string`) provided by ACT.
